config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'
  get 'posts/index'
  get 'posts/show'
  get 'users/show'
  get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Nested routes allow you to capture this relationship in your routing

  resources :users, only: %i[index show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create] 
  end

  # resources :posts, only: [:destroy]

  resources :comments, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:create, :index]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  after_create :set_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
  # Removes one or more objects from the collection by setting their foreign keys to NULL.
  # Objects will be in addition destroyed if they're associated with dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.last(3)
  end

  private

  def set_role
    update(role: 'user')
  end
end

app/controllers/users_controller.rb
# User Controller
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.where(id: params[:id]).includes(:posts).take
  end
end

app/helpers/users_helper.rb
# Users helper
module UsersHelper
end

app/views/users/_user.html.erb
<ul class="user-main">
      <li>
      <img src="https://steelform.com/wp-content/uploads/2017/03/testimonial-avatar-150x150.jpg" alt="user_image" >
      <div>
        <h1><%= @user.name %></h1>
        <p>Number of posts : <%= @user.posts.size %></p>
      </div>
      </li>

</ul>

app/views/users/index.html.erb
<ul class="user-main">
  <% @users.each do |user| %>
    <%= link_to user_path(user) do%>
    <li>
        <% if user.photo %>
        <%= image_tag user.photo %>
        <% else  %>
        <img src="https://steelform.com/wp-content/uploads/2017/03/testimonial-avatar-150x150.jpg" alt="user_image" >
        <% end %>
        <div>
        <h1><%= user.name %></h1>
        <p>Number of posts : <%= user.posts.size %></p>
        </div>
    </li>
    <% end %>
  <% end %>
    
</ul>

app/views/users/show.html.erb
<%= render @user %>

<ul class="user-main">
<li class="user-bio">
    <h3>Bio : </h3>
    <p><%= @user.bio%></p>
</li>


   <% @user.recent_posts.each_with_index do |post, i|%>
        <li class="post-all">
        <h4>Post #<%=i+1%></h4>
        <p><%= post.text%></p>
        <p class="show-li">Coments : <%= post.comments.size%> Likes : <%= post.likes_counter.to_i %> </p>
        </li>
    <%end%>
</ul>


<button class='btn'>
<%= link_to "See all posts", user_posts_path(@user) %>
</button>