config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'
  get 'posts/index'
  get 'posts/show'
  get 'users/show'
  get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Nested routes allow you to capture this relationship in your routing

  resources :users, only: %i[index show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create] 
  end

  # resources :posts, only: [:destroy]

  resources :comments, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:create, :index]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { maximum: 700 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Registers a callback to be called after a record is created
  after_create :update_post_counter

  def update_post_counter
    user.update(posts_counter: user.posts.size)
  end

  def recent_comments
    comments.last(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.all
    render json: { success: true, message: 'Loaded all posts', data: { posts: @posts } }
  end
end

app/controllers/posts_controller.rb
# Posts controller
class PostsController < ApplicationController
  def index
    # @user = User.where(id: params[:user_id]).includes(:posts).take
    if params[:user_id]
      @user = User.find(params[:user_id])
      calc_posts(@user)
    else
      @posts_by_user = Post.all
      render 'allposts'
    end
  end

  def show
    @post = Post.where(id: params[:id]).includes(:comments).take
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = Post.new(post_parameters)
    if @post.save
      flash[:notice] = 'Post created successfully.'
      redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    flash[:success] = 'Post was successfully created.'
    redirect_to user_posts_path(current_user.id)
  end

  private

  def post_parameters
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/helpers/posts_helper.rb
# Posts Helper
module PostsHelper
  def comments?(post)
    return 'All comments' if post.comments.exists?

    'no comments'
  end
end

app/views/posts/index.html.erb
<div class='btn-div'>
    <button>
      <%=link_to 'Back', root_path %>
    </button>

    <button>
      <%=link_to 'Create new Post', new_user_post_path(user_id: @user.id) %>
    </button>
</div>

<%= render @user %>

<ul class="user-main">
    <% @posts_by_user.each_with_index do |post, i|%>
        <li class="post-all">
        <%= link_to user_post_path(@user.id, post.id) do%>
        
            <h4>Post #<%=i+1%></h4>
        <% end %>
            <p><%= post.title%></p>
            <p><%= post.text%></p>
            <p class="show-li">Comments : <%= post.comments.size%>  Likes : <%= post.likes_counter.to_i %> </p>

        
        </li>
        <div class="<%= comments?(post)%> user-comments">
            <% post.recent_comments.each do |comment|%>
                <p>
                <%= User.find(comment.user_id).name %> :
                    <%= comment.text%>
                </p>
            <%end%>
        </div>
    <%end%>
</ul>

app/views/posts/new.html.erb
<%= form_with  model:@post, class:"input-form"  do |f|%>

    <%= f.hidden_field :user_id, value: @user.id %>
    
    <%= f.label :title %><br>
    <%= f.text_field :title,  {:required => true}%><br>

    <%= f.label :text %><br>
    <%= f.text_area :text , {:required => true}%><br>

    <%= f.submit "Create Post", class: "submit" %>
<%end%>

<div class="btn-div">
    <button class="back-btn">
        <%=link_to 'Back', root_path%>
    </button>
</div>

app/views/posts/show.html.erb
<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end %>


<div class="show-post">
    <div class="show-post-user">
    <div>
      <h2>
      Post #<%= @post.user.posts.find_index(@post)+1 %> by:   <%= @post.user.name%>
      </h2>
      <p>
      Comments: <%=@post.comments.size%> Likes: <%=@post.likes_counter.to_i%>
      <%if can? :destroy, @post%>
      <button>
        <%=link_to "Delete", @post, method: :delete%>
      </button>
      <%end%>
      
      </p>
    </div>
    <p><%=@post.title%></p>
    <p><%=@post.text%></p>
    </div>
    <div class="<%= comments?(@post)%> user-comments">
            <% @post.comments.each do |comment|%>
                <p>
                    <%=comment.user.name%> :
                    <%= comment.text%>
                    <%if can? :destroy, comment%>
                    <button>
                        <%=link_to "Delete", comment, method: :delete%>
                    </button>
                    <%end%>
                </p>
            <%end%>
    </div>

</div>

<div>
<%= render partial: 'comments/form'%>
<%= render partial: 'likes/form'%>
<div class="btn-div">
    <button class="back-btn">
        <%=link_to 'Back', user_posts_path(@post.user)%>
    </button>
</div>
</div>